name: Code check

on:
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run check:lint

  tsc:
    runs-on: ubuntu-latest
    name: TypeScript
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - run: npm run check:type

  # https://github.com/changesets/changesets/blob/main/docs/automating-changesets.md#blocking
  changeset:
    runs-on: ubuntu-latest
    name: Changeset
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Check if the pull requests have changesets
        id: check-changeset
        continue-on-error: true
        run: npm run check:changeset

      - name: Error handling
        if: ${{ steps.error_execution.outcome == 'failure' }}
        run: |
          echo "Please add Changesets: npm run changeset"
          echo ${{ steps.error_execution.outcome }}
          exit 1
