name: Deploy to Projection

# the pushing tags event does not work with another github workflow
# so we are using this release event
on:
  release:
    types: [published]

permissions: read-all # This is required to read the secrets

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          URL="${{ secrets.WEBHOOK_URL }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"
