name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create a PR for release workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build the package
        run: npm run build
